In [ ]:
# Initialize Otter
import otter
grader = otter.Notebook("HW0_prog_netid.ipynb")

## Before you start

For this semester, the teaching staff of this course will be using Autograder to grade programming assignment.

Do not run the cell containing `otter` or `grader.check`.  If you try, you will receive an error message (but it will not cause any other problems so don't worry if this happens).

Here are four things we would like you to know before starting. `PLEASE READ CAREFULLY.` Otherwise, you might not receive grades for some questions.

* If you see any blocks containing statements like `grader.check("Qxx")`, please `DO NOT MODIFY` them. You can add new cells to the notebook, but just make sure there is `NO OTHER CELLS` between the answer cells containing tag `# TODO Qxx` and grading cells like 'grader.check("Qxx")`. 

* If the instructions say that you are required to use certain names for output variables, please `FOLLOW THE instructions`. You can still create new variables, but just the make sure to `ASSIGN THE OUTPUT VARIABLES TO CORRECT VALUES`. 

* Some of the print statements are in the comments. Please feel free to use them, but you must `PUT THESE PRINT STATEMENTS IN COMMENTS` before you submit the programming assignment.

* Please `APPEND YOUR NYU NETID` to the name your submission (for example, name your submission as "HW0_prog_abc12345.ipynb" when you submit on Gradescope, and replace <abc1234> with your NYU NetID). 

The autograder does not account for all test cases and edge cases, meaning that it is possible to receive a different grade than what the Autograder assigns you. The teaching staff will grade all submissions manually. Thank you very much for your understanding, and good luck with programming assignment 0!

# Numpy Assignment

Numpy is a library for numerical computing.

This assignment covers the important numpy commands which will be used in all the programming assignments for this course. 

Basics: NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. 

# Array Creation

Numpy arrays behave similar to n-dimensional matrices in matlab.

There are several ways to create an array: Two methods are shown below. Before moving ahead, lets first import numpy.  

In [1]:
# Just run this code cell by pressing shift+enter
import numpy as np

In [2]:
# Method 1 for creating an array: passing a list of numbers.
a=np.array([3,6,2])
print(a)

[3 6 2]


In [3]:
# Create an array b having elements 9,6,3,1. 
# In the code below, remove None and write the numpy command to create an array having these elements. 
b = np.array([9,6,3,1])
print(b)

[9 6 3 1]


In [6]:
grader.check("q1")

NameError: name 'grader' is not defined

 If you simply pass numbers as attributes, this will give an error. example: np.array(9,6,3,1) will give an error. Try it yourself by uncommenting the code cell below, and put it in comments again before submission.

In [ ]:
# b = np.array(9,6,3,1)

Array transforms sequences of sequences into two-dimensional arrays. Sequences of sequences of sequences into three-dimensional arrays, and so on. Run example below which is a 2-dimensional array.

In [7]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


Example of 3-dimensional array:

In [8]:
# Just run this code cell: 
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [28]:
# Create a 2-dimensional array having elemnets [15,16,17] in the first row and [18,19,20 ] in the second row.
d = np.array([[15,16,17],[18,19,20]])
print(d)

[[15 16 17]
 [18 19 20]]


In [ ]:
grader.check("q2")

Method 2 for creating an array: using the "arange" function.  Numpy has a function called arange which is analogous to range function of python. arange function returns array instead of list. Example shown below.

In [4]:
# Run this code cell
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# Run this code cell
f = np.arange(1,10,2)
# Creates an array of 1-dimension. The array values starts at 1, increments by 2 upto 10 (but not including 10). 
print(f)

[1 3 5 7 9]


In [6]:
# Create 1-d array using arange having elements from 1 to 15
g = np.arange(1,16)
print(g)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
grader.check("q3")

# Important attributes of the array object.
Attribute description is given in the comments of the respective code cells.


In [8]:
# Run this cell
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [9]:
# ndarray.ndim gives the number of axes(dimensions) of the array. Run this cell
a.ndim

2

In [10]:
# ndarray.shape gives the tuple having the shape of the array. Run this cell. 
# Here, you can interpret the shape of a as having 2 rows and 3 columns.
a.shape

(2, 3)

In [11]:
# ndarray.size the total number of elements of the array. This is equal to the product of the elements of shape.
a.size

6

In [12]:
# ndarray.dtype an object describing the type of the elements in the array.
a.dtype

dtype('int32')

In [14]:
# Create a numpy array having elements [1,2,3,4,5] in first row and [6,7,8,9,10] in the second row. 
q4 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(q4)
# Find the attributes shown in the above 4 cells.  Write the code below.
q4_dim = q4.ndim
q4_shape = q4.shape
q4_size = q4.size
q4_type = q4.dtype


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
grader.check("q4")

In [16]:
# Sometimes we want to get an individual dimension of an array.  
# We can index which dimension we want from the shape attribute.
print("To get the first dimension:")
print(a.shape[0])
print("To get the second dimension:")
print(a.shape[1])

To get the first dimension:
2
To get the second dimension:
3


# Creating array of zeros and ones.

In [17]:
# Array of zeros. The code below creates an array of zeros of the specified dimension.
# Code below creates an array of zeros of dimension (3,4)
a=np.zeros((3,4))
print(a)
print(a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [18]:
# Array of ones. Here, dtype attribute specifies the data type of the elements of array. This is optional. 
# By default, it is float64 as you can see in the example of zeros above.
# Array of ones with dimensions (2,3,4)
b = np.ones( (2,3,4), dtype=np.int16 )
print(b)
print(b.dtype)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
int16


In [19]:
# Create an array of zeros of dimension (5,6) 
q5= np.zeros((5,6))
print(q5)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
grader.check("q5")

In [21]:
# Create an array of ones of dimension (2,3)
q6= np.ones((2,3))
print(q6)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
grader.check("q6")

# Reshape Function.

Reshape function is used to reshape an array. See the example below. 

In [22]:
a = np.arange(15)
print("The original array a")
print(a)
print("The array a reshaped with dimensions 3x5")
print(a.reshape(3,5))

The original array a
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
The array a reshaped with dimensions 3x5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [23]:
# Reshape function doesn't change the shape of original array. 
print("Notice that a didn't change")
print(a)
print("The dimensions of a:")
print(a.shape)

Notice that a didn't change
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
The dimensions of a:
(15,)


In [24]:
# To change the shape of original array, use this. 
a = a.reshape(3,5)
print("Notice a has been changed")
print(a)
print("The new dimensions of a:")
print(a.shape)

Notice a has been changed
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
The new dimensions of a:
(3, 5)


In [25]:
# Create an array of zeros of dimension (4,5)
q7_a = np.zeros((4,5))
print(q7_a)
# Reshape q7_a to dimensions (10,2).
q7_b = q7_a.reshape(10,2)
print(q7_b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
grader.check("q7")

# Note:
Whenever you use a 1 dimensional array, it is a rank 1 array. In the later assignments, you will see that we don't prefer to use rank 1 array. So, we can convert them to rank 2 using reshape function. 

In [26]:
# Run this cell
# Here we have a rank 1 matrix. See it's shape.
a = np.array([1,2,3])
print(a)
print(a.shape)

[1 2 3]
(3,)


In [27]:
# Run this cell
a = a.reshape((3,1))
# Notice that a changed from a sequence of numbers to a sequence of sequence of numbers
print("The new shape of a")
print(a)
print("The array a's new dimensions:")
print(a.shape)

The new shape of a
[[1]
 [2]
 [3]]
The array a's new dimensions:
(3, 1)


# Numpy.random.rand and Numpy.random.randn

In [29]:
# Numpy.random.rand creates a numpy array of given dimensions where all the elements 
# are random samples from a uniform distribution over [0, 1).
# Run this code cell.
a = np.random.rand(2,3)
print(a)

[[0.73116507 0.01230168 0.2015966 ]
 [0.39619381 0.43219783 0.39331827]]


 Numpy.random.randn creates a numpy array of given dimensions where all the elements are  samples from univariate “normal” (Gaussian) distribution of mean 0 and variance 1

In [31]:
# Run this cell
a = np.random.randn(2,10)
print(a)

[[-1.36552682 -0.33651849 -1.23627794 -2.09816766  1.38176239  1.16037719
  -1.07713592  0.19335089  0.6317004  -1.02009862]
 [ 0.33514841 -0.02024829 -1.1595596  -1.58251686 -1.48517137 -0.48451266
  -0.4980089   0.10237151 -0.36704383 -0.38308624]]


Numpy can create an array having values from the normal distribution with mean = $\mu$, and variance = $\sigma^2$.

To create a random array of elements from $N(\mu, \sigma^2)$, use: sigma = $\sigma$, and mu = $\mu$ and the numpy command:

sigma * np.random.randn(...) + mu

In [32]:
# Two-by-four array of samples from N(3, 6.25):
a=2.5 * np.random.randn(2, 4) + 3
a

array([[ 4.05362441,  3.95158711,  3.12852924,  5.2346876 ],
       [ 2.32207486, -1.69417966, -1.22756104,  4.75413039]])

In [33]:
# Create a numpy array with 3 rows and 5 columns containing random samples with mean (mu)= 5 
# and standard deviation(sigma) = 2
q8 = 2 * np.random.randn(3, 5) + 5
print(q8)

[[ 5.88606287  1.78383784  5.12983065  9.32586997  4.49303185]
 [ 7.94408937  8.77360419  3.78643462  4.65830497  5.28985875]
 [ 5.48348157  4.2921214   3.53505664 -0.05578695  5.60803564]]


In [ ]:
grader.check("q8")

# Basic Operations: 
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [34]:
# Run this code cell
m = np.array( [20,30,40,50] )
n = np.arange( 1,5 )
print("The array m:")
print(m)
print("The array n:")
print(n)

The array m:
[20 30 40 50]
The array n:
[1 2 3 4]


In [35]:
# To subtract corresponding elements of array n from array m , simply write m - n as shown below
sub = m-n
print(sub)

[19 28 37 46]


In [36]:
# similarly we can do addition, multiplication, division of corresponding elements. Complete the code to add, multiply and divide corresponding elements of m and n.
addition = m + n
product = m * n
ratio = m / n
print("m + n:")
print(addition)
print("m * n: ")
print(product)
print("m / n:")
print(ratio)

m + n:
[21 32 43 54]
m * n: 
[ 20  60 120 200]
m / n:
[20.         15.         13.33333333 12.5       ]


In [ ]:
grader.check("q9")

In [37]:
# Square all the elements of the array n and save it in an array called 'square' by writing n**2
square = n**2
print(square)

[ 1  4  9 16]


In [38]:
# Take sine of all the elements of a matrix and save it in another matrix sine
sine=10*np.sin(m)
print(sine)

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [39]:
# Run this cell to see how this works
e= m<35
print(e)

[ True  True False False]


In [40]:
# In Python 'True' evaluates to 1 and 'False' evaluates to 0.  
# We can count how many times an item in m was less than 35 by summing the items in e
print(np.sum(e))

2


In [41]:
# Run this cell to convert a boolean array into an int array
i = e.astype(int)
print(i)

[1 1 0 0]


# Matrix and vector operations

Unlike in many matrix languages (like matlab), the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or the dot method:

In [42]:
# Run this cell
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0], [3,4]] )
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [43]:
# Element wise product. Note: Dimensions should be same for A and B
C = A * B
print(C)

[[2 0]
 [0 4]]


In [44]:
# The dot method for matrix multiplication.
# Dimensions should be in accordance to linear algbra rule of Matrix-Matrix or Matrix-Vector multiplication.
D = A.dot(B) 
print(D)

[[5 4]
 [3 4]]


In [45]:
# Another way to multiply matrices is to use np.dot() function.
D = np.dot(A,B)
print(D)

[[5 4]
 [3 4]]


In [48]:
# Create a random matrix of dimension (3,4) and another random matrix of dimension (4,2) and find their dot product. 
# Also, check the dimensions of the resultant matrix.
mat1= np.random.randn(3, 4)
mat2= np.random.randn(4,2)
dot_product= mat1.dot(mat2)
print("mat1:")
print(mat1)
print("mat2:")
print(mat2)
print("mat1 times mat2:")
print(dot_product)

mat1:
[[ 1.6611804   0.4150876   0.54853426  0.98859255]
 [ 1.25463231  1.01892006 -0.8474579   1.39846676]
 [-0.85255153 -1.74798096  1.86613686 -0.8436183 ]]
mat2:
[[-1.18612169  0.36467823]
 [ 1.10026925  0.8010002 ]
 [-1.13789529 -0.3451244 ]
 [ 0.16679517  0.99495191]]
mat1 times mat2:
[[-1.97293607  1.73257106]
 [ 0.83051567  2.95757784]
 [-3.17619964 -3.19444908]]


In [ ]:
grader.check("q10")

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [49]:
# Run this cell
q11 = np.random.random((2,3))
print(q11)

[[0.33902861 0.80666548 0.33715763]
 [0.46938413 0.33698819 0.7472421 ]]


In [50]:
# Calculating sum of all the elements of the array. 
# This method considers all the elements of array as a long list of numbers regardless of the shape.
add = q11.sum()
print(add)

3.036466145360703


In [51]:
# Find minimum and maximum from all the elements using q11.min() and q11.max() command.
minimum = q11.min()
maximum = q11.max()
print("minimum = %9.8f"%(minimum))
print("maximum = %9.8f"%(maximum))

minimum = 0.33698819
maximum = 0.80666548


In [ ]:
grader.check("q11")

In [53]:
# Create a random array a of dimension (4,6) and find sum , min, max as shown above.
arr = np.random.randn(4,6)
add = arr.sum()
minimum_arr = arr.min()
maximum_arr = arr.max()
print("The array arr:")
print(arr)
print("The sum of all elements of array arr: %9.8f"%(add))
print("minimum = %9.8f"%(minimum_arr))
print("maximum = %9.8f"%(maximum_arr))

The array arr:
[[ 0.47255984  0.74238893  0.13099655  0.37373555  0.76314184  1.88423402]
 [-0.36017057  0.87600417 -0.15710852 -1.39125531 -0.56234346  0.4872752 ]
 [ 0.19836952  2.15015915 -0.50510311 -1.41483053 -0.24456322 -0.42219325]
 [ 0.76062133  1.04346767  0.81514074 -0.90211785 -0.14243542 -1.69024436]]
The sum of all elements of array arr: 2.90572886
minimum = -1.69024436
maximum = 2.15015915


In [ ]:
grader.check("q12")

# Operations on rows or columns

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [54]:
# Run this cell
B = np.arange(12).reshape(3,4)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [55]:
# sum along a column
column_sum = B.sum(axis=0)  
print(column_sum)

[12 15 18 21]


In [56]:
# sum along a row. In sum function above, in place of axis=0, pass axis=1
row_sum = B.sum(axis=1)
print("The row sums:")
print(row_sum)
# Minimum along row
min_row= B.min(axis=1)
print("The minimum item in every row:")
print(min_row)
# Minimum along column
min_column= B.min(axis=0)
print("The minimum item in every column:")
print(min_column)

The row sums:
[ 6 22 38]
The minimum item in every row:
[0 4 8]
The minimum item in every column:
[0 1 2 3]


In [ ]:
grader.check("q13")

In [57]:
# To apply universal mathematical functions on all the elements of a matrix, we do so as shown below:
B = np.arange(3)
print("The array B:")
print(B)
# Compute exponent of every element of B
C = np.exp(B) 
print("The array C:")
print(C)
# Compute sqrt of every element in B.  (You may get an error if an element in B is negative.)
D = np.sqrt(B)
print("The array D:")
print(D)

The array B:
[0 1 2]
The array C:
[1.         2.71828183 7.3890561 ]
The array D:
[0.         1.         1.41421356]


In [60]:
# Create a random matrix of dimensions (2,4) and apply the above three operations.
q14_mat = np.random.rand(2,4) + 1
print("The matrix:")
print(q14_mat)
# Apply operations on matrix: exp and sqrt
q14_exp = np.exp(q14_mat)
print(q14_exp)
q14_sqrt = np.sqrt(q14_mat)
print(q14_sqrt)
# Perform np.log( ).  (Note: you will get error if you try to take the log of a negative number.)
q14_log = np.log(q14_mat)
print(q14_log)

The matrix:
[[1.20088856 1.52386833 1.26142788 1.56737988]
 [1.61296663 1.24234417 1.5030243  1.29128247]]
[[3.32306834 4.58994634 3.53045895 4.79407066]
 [5.01767476 3.46372352 4.49526357 3.63744849]]
[[1.09585061 1.23445062 1.12313306 1.25195043]
 [1.27002623 1.11460494 1.22597892 1.13634611]]
[[0.18306175 0.42125206 0.23224431 0.44940536]
 [0.47807511 0.21700006 0.40747928 0.25563589]]


In [ ]:
grader.check("q14")

# Transpose of a Matrix
There are 2 ways to get transpose of a numpy array. Either using .T attribute or using np.transpose(matrix) method.
Note: If you have a rank 1 matrix and you take it's transpose, it will be same as the original matrix.

In [61]:
# Using .T attribute
A = np.arange(4).reshape((2,2))
B = A.T
print("The original A:")
print(A)
print("The transpose of A:")
print(B)

The original A:
[[0 1]
 [2 3]]
The transpose of A:
[[0 2]
 [1 3]]


In [62]:
# Using transpose method
C = np.transpose(A)
print(C)

[[0 2]
 [1 3]]


In [63]:
# Create a random matrix X of dimension (4,3) and take it's transpose.
X = np.random.randn(4,3)
# Find transpose of X using any of the above method
Y = X.T
print("X: ")
print(X)
print("X Transpose: ")
print(Y)

X: 
[[ 2.50072445 -1.1253289   1.37997402]
 [-1.49131755 -0.2682269   0.52755387]
 [ 0.77913599  0.69792507  0.86760951]
 [-0.01832269  0.12471815  0.24314946]]
X Transpose: 
[[ 2.50072445 -1.49131755  0.77913599 -0.01832269]
 [-1.1253289  -0.2682269   0.69792507  0.12471815]
 [ 1.37997402  0.52755387  0.86760951  0.24314946]]


In [ ]:
grader.check("q15")

# Inner vs Outer Product

The `dot` function behaves differently if the numpy arrays are 1-d instead of 2-d.

In [64]:
# Creating two 1-dimensional numpy arrays

a = np.arange(1,5)
print(a)
print(a.shape)

b = np.arange(5,9)
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[5 6 7 8]
(4,)


In [65]:
# Inner product with 1-dimensional arrays
# If a and b are 1-dimensional arrays, taking the transpose doesn't do anything!

print(a.T)

# So we can just take the dot product without worry
c = a.dot(b)
print(c)

[1 2 3 4]
70


In [66]:
# Inner product with 2-dimensional arrays

# First we create 2-d arrays using reshape
a_2d = a.reshape((a.shape[0],1))
print(a_2d)
print(a_2d.shape)

b_2d = b.reshape((b.shape[0],1))
print(b_2d)
print(b_2d.shape)

# When we use 2-d numpy arrays things work differently
# uncomment the next line and see what happens!
# a_2d.dot(b_2d)

# Inner product
# To multipy 2-d numpy arrays, we have to make sure the dimensions match.  So we take the dot product of a_2d.T with b_2d
# a_2d.T has dimension 1x4 and b_2d has dimension 4x1 so the result is 1x1
c = a_2d.T.dot(b_2d)
print(c)
print(c.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[5]
 [6]
 [7]
 [8]]
(4, 1)
[[70]]
(1, 1)


In [67]:
# Outer product
# What do you think happens if we take the dot product of a_2d with b_2d.T?  Run the following cell to find out!
d = a_2d.dot(b_2d.T)
print(d)

[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


You multiplied a 4x1 matrix with a 1x4 matrix.  This created a 4x4 matrix.

# Indexing, slicing and iterating

Indexing, slicing and iterating on 1-dimensional arrays. 

Indexing, slicing and iterating is almost same as simple python lists for 1-dimensional arrays. 

Note: Index starts from 0.

In [68]:
# Run this cell
a = np.arange(15)**3
print(a)

[   0    1    8   27   64  125  216  343  512  729 1000 1331 1728 2197
 2744]


In [70]:
# Indexing. Getting third element of a
third_elem = a[2]
print(third_elem)
# Find fifth element of a
fifth_elem= a[4]
print(fifth_elem)

8
64


In [ ]:
grader.check("q16")

In [72]:
# Slicing. Getting elements from index 2 to 5.  (Note we do not get the item at index 6.)
slice = a[2:6]
print(slice)
# Find elements from index 4 to 7.
slice_2 = a[4:8]
print(slice_2)

[  8  27  64 125]
[ 64 125 216 343]


In [ ]:
grader.check("q17")

In [73]:
# Reversing 1-D array
rev = a[::-1]
print(rev)

[2744 2197 1728 1331 1000  729  512  343  216  125   64   27    8    1
    0]


In [74]:
# Looping over some indices.
# Start from index 2, stop before index 12 and jump or increment by 3.
q18_example = a[2:12:3]
print(q18_example)
# From array a, start from index 3, stop before index 12 and jump by 4.
q18_exercise = a[3:12:4]
print(q18_exercise)

[   8  125  512 1331]
[  27  343 1331]


In [ ]:
grader.check("q18")

In [75]:
# Using a for loop to iterate:
for i in a:
    print(i)

0
1
8
27
64
125
216
343
512
729
1000
1331
1728
2197
2744


# Multidimensional arrays 
They can have one index per axis. These indices are given in a tuple separated by commas:

In [76]:
# Run this code
a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [77]:
# Element in third row and second column of the matrix.  
# Note due to indexing starting from 0, we use index 2 for the third row and we use index 1 for the second column
print(a[2,1])

7


In [79]:
# Find element in second row and third column of a. 
q19 = a[1,2]
print(q19)

5


In [ ]:
grader.check("q19")

In [80]:
# Getting each row in the second column of array a
c = a[: , 1]
print(c)

[ 1  4  7 10]


In [81]:
# Get each column in the second row of a.
q20 = a[1 , :]
print(q20)

[3 4 5]


In [ ]:
grader.check("q20")

In [82]:
# a[i:j, : ] returns rows i+1 through j of the matrix.  (Yeah this is confusing due to indexing starting at 0!)
# In the code below we get rows 2 through 3 of the matrix.  (We index from 1 to (3-1).) 
e = a[1:3, : ]
print(e)

[[3 4 5]
 [6 7 8]]


In [83]:
# Get the last row
b = a[-1,:]
print(b)

[ 9 10 11]


In [84]:
# Find last column
q21 = a[: , -1]
print(q21)

[ 2  5  8 11]


In [ ]:
grader.check("q21")

You can use a for loop to traverse through an array!!

In [85]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

0
1
2
3
4
5
6
7
8
9
10
11


# Stacking together different arrays.

Several arrays can be stacked together along different axes:

In [86]:
# Run this cell
q22_a = np.arange(4).reshape((2,2))
print(q22_a)

[[0 1]
 [2 3]]


In [87]:
# Run this cell
q22_b = np.arange(4,8).reshape((2,2))
print(q22_b)

[[4 5]
 [6 7]]


To stack array b at the bottom of array a, we use vstack command. Note, for vstack, number of columns in both arrays should be same i.e. a.shape[1] == b.shape[1].

In [88]:
# Stacking b at the bottom of a.
q22_c = np.vstack((q22_a,q22_b))
print(q22_c)
print(q22_c.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [89]:
# Horizontal stack. Stack a to the left of b. 
# Note, for hstack, number of rows in both arrays should be same i.e. a.shape[0] == b.shape[0].
q22_d = np.hstack((q22_a,q22_b))
print(q22_d)

[[0 1 4 5]
 [2 3 6 7]]


In [91]:
# Create an array a of dimension (3,2) and another array b of dimension (3,5). 
# Append one of them to the left of another i.e. hstack.
q22_arr_a= np.arange(6).reshape((3,2))
q22_arr_b= np.arange(6, 21).reshape((3,5))
q22_left = np.hstack((q22_arr_a, q22_arr_b))
print("The array a:")
print(q22_arr_a)
print("The array b:")
print(q22_arr_b)
print("The array left:")
print(q22_left)

The array a:
[[0 1]
 [2 3]
 [4 5]]
The array b:
[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
The array left:
[[ 0  1  6  7  8  9 10]
 [ 2  3 11 12 13 14 15]
 [ 4  5 16 17 18 19 20]]


In [ ]:
grader.check("q22")

# Broadingcasting.

This is an important feature of numpy arrays. Suppose we have an array a of dimension (4,5) and another array b of dimension (4,1). If we want to add both the arrays, is it possible according to linear algebra? The answer is NO because in Linear Algebra, to perform element-wise arithmetic operations, dimensions should be same. 

However, using broadcasting it is possible to add the arrays. Broadcasting copies the first column of b to other columns of b to make it of same size as of a i.e. make it of dimension (4,5) from (4,1). 

In [92]:
a = np.arange(20).reshape((4,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [93]:
b = np.arange(4).reshape((4,1))
print(b)

[[0]
 [1]
 [2]
 [3]]


In [94]:
c = a + b
print(c)

[[ 0  1  2  3  4]
 [ 6  7  8  9 10]
 [12 13 14 15 16]
 [18 19 20 21 22]]


For broadcasting to work, all the dimensions must be compatible. A dimension is compatible for both arrays either if  they are equal, or either of them is 1.  

For example: array b has dimensions (2,3,4) and array c has dimensions (1,3,2).  The first dimension is compatible because c.shape[0]=1.  The second dimension is compatible because b.shape[1]==c.shape[1].  But the third dimension is not compatible becaue b.shape[2] $\not =$ c.shape[2] and neither of them is 1.

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. 

When either of the dimensions compared is one, the other is used. In other words, dimensions with size 1 are stretched or “copied” to match the other.
In the following example, both the A and B arrays have axes with length one that are expanded to a larger size during the broadcast operation:

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

Another example:

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

Broadcasting rules can be confusing. But for now, you only need to know very basic broadcasting which is shown in the code cell above.

# Basic Linear Algebra Operations.

In [95]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [96]:
# To find Inverse of matrix a:
b = np.linalg.inv(a)
print(b)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [97]:
# Creating Identity matrix: Identity matrix is always a square matrix.
u = np.eye(3)
print(u)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [98]:
# Finding Trace of a matrix
c = np.trace(u)
print(c)

3.0


In [99]:
# Find eigen values of a matrix
d = np.linalg.eig(a)
print(d)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


# Automatic Reshaping

In [100]:
# Run this cell
a = np.arange(30)
a.shape = 2,-1,3  # -1 means "whatever is needed"
print(a.shape)
print(a)

(2, 5, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


This assignment ends here. We hope this assignment gives you basic knowledge of using numpy and it's arrays and perform basic operations. We highly encourage you to use official numpy documentation if you need more help while solving your machine learning assignments. https://docs.scipy.org/doc/numpy-dev/user/quickstart.html . One of the topic not covered in this assignment is indexing with arrays of indices and indexing with  boolean arrays. Though not used much in the programming assignments, but can be helpful in some scenarios. You can find them in the given link above.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=aa9311e4-5d9b-4428-960e-eeb7e41483f1' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [101]:
grader.check_all()

NameError: name 'grader' is not defined

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

Please submit your homework on Gradescope.

In [ ]:
# Save your notebook first, then run this cell to export your submission.
grader.export()